baseURL: http://amsimp.github.io/
languageCode: en-uk
title: AMSIMP
theme: hugo-fresh
disableKinds: ["taxonomyTerm"]
googleAnalytics: UA-131031265-2
DefaultContentLanguage: en
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: An open-source solution which leverages machine learning to improve numerical weather prediction
  navColor: blue
  navbarlogo:
    image: logos/amsimp.svg
    link: /
  font:
    name: "Lato"
    sizes: [400,900]
  hero:
    # Main hero title
    title: AMSIMP
    # Hero subtitle (optional)
    subtitle: An open-source solution which leverages machine learning to improve numerical weather prediction
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/install"
    # Hero image (from static/images/___)
    image: logos/amsimp.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  news:
    title: AMSIMP Developer Blog is LIVE!
    content: get the latest news on the developments with AMSIMP
    url: /news

  shell:
    title: placeholder
  vars:
    title: PROGNOSTIC VARIABLES
    features:
    - title: 2 metre temperature
      text: The 2 metre temperature field gives forecasters a general idea of what the temperature is now and what it will be in the future at the Earth's surface.
      img: images/content_images/vars/t2m.png
      alttext: Example 2 metre temperature prediction from the AMSIMP GFM.
      url: https://apps.ecmwf.int/codes/grib/param-db?id=167
    - title: 850 hPa air temperature
      text: The second air temperature parameter is at a pressure surface of 850 hPa. The 850 hPa pressure surface is usually above the planetary boundary layer and therefore not affected by diurnal variations but provides information about broader temperature trends. 
      img: images/content_images/vars/t.png
      alttext: Example 850 hPa air temperature prediction from the AMSIMP GFM.
      url: https://apps.ecmwf.int/codes/grib/param-db/?id=130
    - title: 500 hPa geopotential
      text: Geopotential at 500 hPa pressure is a commonly used variable that encodes the synoptic-scale pressure distribution. It is the standard verification variable for most medium-range numerical weather prediction models.
      img: images/content_images/vars/z.png
      alttext: Example 500 hPa air temperature prediction from the AMSIMP GFM.
      url: https://apps.ecmwf.int/codes/grib/param-db/?id=129

  keyfeatures:
    features:
    - title: Powerful Neural Networks
      text: Fast and accurate, AMSIMP's neural networks provide high quality weather forecasts and predictions.
    - title: Operational Model
      text: AMSIMP offers a pretrained operational model architecture. It is trained on a dataset from the past decade, ranging from the year 2009 to the year 2016.
    - title: Near Real-Time NWP
      text: AMSIMP offers near real-time numerical weather prediction through initialisation conditions provided by the Global Data Assimilation System.
    - title: Performance
      text: The core of AMSIMP is well-optimized Python code. A performance increase of 6.18 times can be expected in comparison against a physics-based model of a similar resolution.
    - title: Easy to use
      text: AMSIMP's high level and intuitive syntax makes it accessible for programmers and atmospheric scientists of any experience level.
    - title: Open source
      text: Distributed under the [GNU General Public License v3.0](https://github.com/amsimp/amsimp/blob/master/LICENSE), AMSIMP is developed [publicly on GitHub](https://github.com/amsimp/amsimp).

languages:
  en:
    title: AMSIMP
    languageName: English
    weight: 1
    contentDir: content/en
    navbar:
      - title: Install
        url: /install
      - title: Documentation
        url: https://docs.amsimp.com
      - title: Roadmap
        url: /roadmap
      - title: Community
        url: /community
      - title: About Us
        url: /about
      - title: Contribute
        url: /contribute
    footer:
      logo: footer.png
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/amsimp/amsimp
        icon: github
      - link: https://twitter.com/amsimp_team
        icon: twitter
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /install
            - text: Documentation
              link: https://docs.amsimp.com
            - text: Roadmap
              link: /roadmap
            - text: GitHub organisation
              link: https://github.com/amsimp
        column2:
          links:
            - text: About us
              link: /about
            - text: Community
              link: /community
            - text: Contribute
              link: /contribute
            - text: Code of conduct
              link: /code-of-conduct
